name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.${project.name}Plugin
author: PureGero
website: https://github.com/PureGero/ViaVersionAutoUpdater
api-version: 1.13
folia-supported: true
multipaper-supported: true